### ISSUE TITLE
[TODO] 앞으로 해야할 것.

### ISSUE THREAD

**Issue by tkddn9316** [tkddn9316/Seoullo_new#1]
## Todo v1.0.2
- [x] PlaceList 로딩 시 ProgressBar
- [x] 각 API 호출마다 sealed class로 상태 감지
- [x] paging 할 때마다 프로그래스 바
- [x] NearbyList에 places.rating,places.userRatingCount 추가
- [x] NearbyList에 FAB으로 별점 순 정렬, 이름 순 정렬 추가(맨 밑 스크롤시 GONE)
- [x] 세부 화면에 reviews(최대 5개),googleMapsLinks(reviewUri) 추가(+ 이전 화면: displayName, formattedAddress, openNow, weekdayDescriptions, rating, userRatingCount)
- [x] 세부 화면은 걍 분기처리가 나을 수도...?(일반, nearby)
- [x] 설정->로그아웃
- [x] Select Places에 검색 시 연관 장소 나타냄
https://www.youtube.com/watch?v=B0cvzzjH6jc : 연관 검색어 UI
https://developers.google.com/maps/documentation/places/web-service/place-autocomplete?hl=ko : Google Places 자동 완성

## Todo v1.0.7
- [x] 여행 리스트 세부 화면 진입 시 Local DB 저장, 하루 지나면 삭제(WorkManager), 메인 화면에서 오늘 본 리스트 보여주기
- [x] Google 로그인 마이그레이션
Android용 Google 로그인 에서 Android Credential Manager로 마이그레이션
- [ ] tourAPI로 불러온 리스트에서도 리뷰 시스템 추가하기(firebase firestore 예정) - Google 로그인 마이그레이션 이후 작업
- [ ] libs.versions 파일 정리
- [ ] 첫 진입 시 onBoarding(소개 및 사용법), 처음 보면 없어지지만 설정 창에서 추가로 볼 수도 있음.
- [ ] 세부 화면 전화번호 있으면 버튼 추가, 전화 걸기 기능 추가
- [ ] 메인 화면 축제 이미지 클릭 시 축제 세부 화면으로
- [ ] github action을 이용한 CI/CD 예정(일단 공부 해야함)
- [ ] 인앱 업데이트 구현(유연, 즉시)
- [ ] 실패 시 재시도 로직(스낵바)
